DROP DATABASE IF EXISTS giphyquotes;
CREATE DATABASE giphyquotes;

\c giphyquotes;

CREATE TABLE author (
	ID SERIAL PRIMARY KEY,
	Name TEXT
);

CREATE TABLE caption (
    ID SERIAL PRIMARY KEY,
	Sentence TEXT
);

CREATE TABLE giphyURL (
	ID SERIAL PRIMARY KEY,
	Url TEXT
);